import java.util.*;
import java.lang.*;
import java.io.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        int option;


        boolean y = true;
        boolean n = false;

        HashMap c1 = new HashMap();
        c1.put("name","cat");
        c1.put("bnana fvrt food",n);
        c1.put("domestic animal",y);
        c1.put("social animal",y);
        c1.put("pet animal",y);
        c1.put("mammal",y);
        c1.put("cannot taste anything sweet",y);
        c1.put("carnivores",y);
        c1.put("primates",n);
        c1.put("fingerprints like human",n);
        c1.put("sleep while sitting",n);
        c1.put("omnivores",n);
        c1.put("leaping trees",n);
        c1.put("famous for loyality",n);
        c1.put("used by police",n);
        c1.put("herbivores",n);
        c1.put("black and white strips",n);
        c1.put("tallest",n);
        c1.put("long legs",n);
        c1.put("long neck",n);
        c1.put("brown spots on body",n);
        c1.put("livstock of meat and milk",n);
        c1.put("hides are used for making leather products",n);
        c1.put("sensitive skin",n);
        c1.put("poor eyesight",n);
        c1.put("roll in mud",n);
        c1.put("chew up wires",n);
        c1.put("eat paper",n);
        c1.put("sharp teeth",n);
        c1.put("small in size",n);
        c1.put("6 fingers",n);
        c1.put("love to eat",n);
        c1.put("favourite foood bamboo",n);
        c1.put("a good swimmer",n);
        c1.put("screw-horned goat",n);
        c1.put("national animal",n);
        c1.put("short legs",n);
        c1.put("short tail",n);
        c1.put("greyish to muddy brown skin",n);
        c1.put("secnd largest land animal",n);
        c1.put("nose and eyes are the top of its head",n);
        c1.put("get water from plants",n);
        c1.put("king of a jungle",n);
        c1.put("carrying heavy loads",n);
        c1.put("reputation for stubbornness",n);
        c1.put("hoping and bouncing",n);
        c1.put("pouch",n);
        c1.put("big feets",n);
        c1.put("big cat species",n);
        c1.put("largest cat species in the world",n);
        c1.put("dark vertical stripes anf orange fur",n);
        c1.put("nocturnal animal",n);
        c1.put("solitary creature",n);

        c1.put(" light coloured and have dark spots on their fur.",n);
        c1.put(" skilled climber",n);
        c1.put(" Leopards are the smallest of the large cat family",n);
        c1.put(" 40 gallons in one go",n);
        c1.put("go for weeks without drinking water",n);

        c1.put("store fat and energy in parts of their bodies known as humps",n);
        c1.put("Can Hydrate Quickly",n);
        c1.put("picky eater",n);
        c1.put("four-compartment stomach",n);
        c1.put("dont have teeth on upper jaw",n);
        c1.put("dislike water",n);
        c1.put(" extremely intelligent animals capable of problem solving",n);
        c1.put(" best known for wool",n);
//----------------------------------------------------------
        HashMap c2 = new HashMap();
        c2.put("name","monkey");
        c2.put("bnana fvrt food",y);
        c2.put("domestic animal",n);
        c2.put("social animal",y);
        c2.put("pet animal",n);
        c2.put("mammal",y);
        c2.put("cannot taste anything sweet",n);
        c2.put("carnivores",n);
        c2.put("primates",y);
        c2.put("fingerprints like human",y);
        c2.put("sleep while sitting",y);
        c2.put("omnivores",y);
        c2.put("leaping trees",y);
        c2.put("famous for loyality",n);
        c2.put("used by police",n);
        c2.put("herbivores",n);
        c2.put("black and white strips",n);
        c2.put("livstock of meat and milk",n);
        c2.put("hides are used for making leather products",n);
        c2.put("sensitive skin",n);
        c2.put("poor eyesight",n);
        c2.put("roll in mud",n);
        c2.put("chew up wires",n);
        c2.put("eat paper",n);
        c2.put("sharp teeth",n);
        c2.put("small in size",n);
        c2.put("6 fingers",n);
        c2.put("love to eat",n);
        c2.put("favourite foood bamboo",n);
        c2.put("a good swimmer",n);
        c2.put("screw-horned goat",n);
        c2.put("national animal",n);
        c2.put("short legs",n);
        c2.put("short tail",n);
        c2.put("greyish to muddy brown skin",n);
        c2.put("secnd largest land animal",n);
        c2.put("nose and eyes are the top of its head",n);
        c2.put("get water from plants",n);
        c2.put("king of a jungle",n);
        c2.put("carrying heavy loads",n);
        c2.put("reputation for stubbornness",n);
        c2.put("hoping and bouncing",n);
        c2.put("pouch",n);
        c2.put("big feets",n);
        c2.put("big cat species",n);
        c2.put("largest cat species in the world",n);
        c2.put("dark vertical stripes anf orange fur",n);
        c2.put("nocturnal animal",n);
        c2.put("solitary creature",n);

        c2.put(" light coloured and have dark spots on their fur.",n);
        c2.put(" skilled climber",n);
        c2.put(" Leopards are the smallest of the large cat family",n);
        c2.put(" 40 gallons in one go",n);
        c2.put("go for weeks without drinking water",n);

        c2.put("store fat and energy in parts of their bodies known as humps",n);
        c2.put("Can Hydrate Quickly",n);
        c2.put("picky eater",n);
        c2.put("four-compartment stomach",n);
        c2.put("dont have teeth on upper jaw",n);
        c2.put("dislike water",n);
        c2.put(" extremely intelligent animals capable of problem solving",n);
        c2.put(" best known for wool",n);
//----------------------------------------------------------
        HashMap c3 = new HashMap();
        c3.put("name","dog");
        c3.put("bnana fvrt food",n);
        c3.put("domestic animal",y);
        c3.put("social animal",y);
        c3.put("pet animal",y);
        c3.put("mammal",y);
        c3.put("cannot taste anything sweet",n);
        c3.put("carnivores",n);
        c3.put("primates",n);
        c3.put("fingerprints like human",n);
        c3.put("sleep while sitting",n);
        c3.put("omnivores",y);
        c3.put("leaping trees",n);
        c3.put("famous for loyality",y);
        c3.put("used by police",y);
        c3.put("herbivores",n);
        c3.put("black and white strips",n);
        c3.put("world's largest land animal",y);
        c3.put("large flat ears",y);
        c3.put("long trunk",y);
        c3.put("tallest",n);
        c3.put("long legs",n);
        c3.put("long neck",n);
        c3.put("brown spots on body",n);
        c3.put("livstock of meat and milk",n);
        c3.put("hides are used for making leather products",n);
        c3.put("sensitive skin",n);
        c3.put("poor eyesight",n);
        c3.put("roll in mud",n);
        c3.put("chew up wires",n);
        c3.put("eat paper",n);
        c3.put("sharp teeth",n);
        c3.put("small in size",n);
        c3.put("6 fingers",n);
        c3.put("love to eat",n);
        c3.put("favourite foood bamboo",n);
        c3.put("a good swimmer",n);
        c3.put("screw-horned goat",n);
        c3.put("national animal",n);
        c3.put("short legs",n);
        c3.put("short tail",n);
        c3.put("greyish to muddy brown skin",n);
        c3.put("secnd largest land animal",n);
        c3.put("nose and eyes are the top of its head",n);
        c3.put("get water from plants",n);
        c3.put("king of a jungle",n);
        c3.put("carrying heavy loads",n);
        c3.put("reputation for stubbornness",n);
        c3.put("hoping and bouncing",n);
        c3.put("pouch",n);
        c3.put("big feets",n);
        c3.put("big cat species",n);
        c3.put("largest cat species in the world",n);
        c3.put("dark vertical stripes anf orange fur",n);
        c3.put("nocturnal animal",n);
        c3.put("solitary creature",n);

        c3.put(" light coloured and have dark spots on their fur.",n);
        c3.put(" skilled climber",n);
        c3.put(" Leopards are the smallest of the large cat family",n);
        c3.put(" 40 gallons in one go",n);
        c3.put("go for weeks without drinking water",n);

        c3.put("store fat and energy in parts of their bodies known as humps",n);
        c3.put("Can Hydrate Quickly",n);
        c3.put("picky eater",n);
        c3.put("four-compartment stomach",n);
        c3.put("dont have teeth on upper jaw",n);
        c3.put("dislike water",n);
        c3.put(" extremely intelligent animals capable of problem solving",n);
        c3.put(" best known for wool",n);
//----------------------------------------------------------
        HashMap c4 = new HashMap();
        c4.put("name","zebra");
        c4.put("bnana fvrt food",n);
        c4.put("domestic animal",n);
        c4.put("social animal",y);
        c4.put("pet animal",n);
        c4.put("mammal",y);
        c4.put("cannot taste anything sweet",n);
        c4.put("carnivores",n);
        c4.put("primates",n);
        c4.put("fingerprints like human",n);
        c4.put("sleep while sitting",n);
        c4.put("omnivores",n);
        c4.put("leaping trees",n);
        c4.put("famous for loyality",n);
        c4.put("used by police",n);
        c4.put("herbivores",y);
        c4.put("black and white strips",y);
        c4.put("world's largest land animal",y);
        c4.put("large flat ears",y);
        c4.put("long trunk",y);
        c4.put("tallest",n);
        c4.put("long legs",n);
        c4.put("long neck",n);
        c4.put("brown spots on body",n);
        c4.put("livstock of meat and milk",n);
        c4.put("hides are used for making leather products",n);
        c4.put("sensitive skin",n);
        c4.put("poor eyesight",n);
        c4.put("roll in mud",n);
        c4.put("chew up wires",n);
        c4.put("eat paper",n);
        c4.put("sharp teeth",n);
        c4.put("small in size",n);
        c4.put("6 fingers",n);
        c4.put("love to eat",n);
        c4.put("favourite foood bamboo",n);
        c4.put("a good swimmer",n);
        c4.put("screw-horned goat",n);
        c4.put("national animal",n);
        c4.put("short legs",n);
        c4.put("short tail",n);
        c4.put("greyish to muddy brown skin",n);
        c4.put("secnd largest land animal",n);
        c4.put("nose and eyes are the top of its head",n);
        c4.put("get water from plants",n);
        c4.put("king of a jungle",n);
        c4.put("carrying heavy loads",n);
        c4.put("reputation for stubbornness",n);
        c4.put("hoping and bouncing",n);
        c4.put("pouch",n);
        c4.put("big feets",n);
        c4.put("big cat species",n);
        c4.put("largest cat species in the world",n);
        c4.put("dark vertical stripes anf orange fur",n);
        c4.put("nocturnal animal",n);
        c4.put("solitary creature",n);

        c4.put(" light coloured and have dark spots on their fur.",n);
        c4.put(" skilled climber",n);
        c4.put(" Leopards are the smallest of the large cat family",n);
        c4.put(" 40 gallons in one go",n);
        c4.put("go for weeks without drinking water",n);

        c4.put("store fat and energy in parts of their bodies known as humps",n);
        c4.put("Can Hydrate Quickly",n);
        c4.put("picky eater",n);
        c4.put("four-compartment stomach",n);
        c4.put("dont have teeth on upper jaw",n);
        c4.put("dislike water",n);
        c4.put(" extremely intelligent animals capable of problem solving",n);
        c4.put(" best known for wool",n);
//----------------------------------------------------------
        HashMap c5 = new HashMap();
        c5.put("name","elephant");
        c5.put("bnana fvrt food",n);
        c5.put("domestic animal",n);
        c5.put("social animal",y);
        c5.put("pet animal",n);
        c5.put("mammal",y);
        c5.put("cannot taste anything sweet",n);
        c5.put("carnivores",n);
        c5.put("primates",n);
        c5.put("fingerprints like human",n);
        c5.put("sleep while sitting",n);
        c5.put("omnivores",n);
        c5.put("leaping trees",n);
        c5.put("famous for loyality",n);
        c5.put("used by police",n);
        c5.put("herbivores",y);
        c5.put("black and white strips",n);
        c5.put("world's largest land animal",y);
        c5.put("large flat ears",y);
        c5.put("long trunk",y);
        c5.put("tallest",n);
        c5.put("long legs",n);
        c5.put("long neck",n);
        c5.put("brown spots on body",n);
        c5.put("livstock of meat and milk",n);
        c5.put("hides are used for making leather products",n);
        c5.put("sensitive skin",n);
        c5.put("poor eyesight",n);
        c5.put("roll in mud",n);
        c5.put("chew up wires",n);
        c5.put("eat paper",n);
        c5.put("sharp teeth",n);
        c5.put("small in size",n);
        c5.put("6 fingers",n);
        c5.put("love to eat",n);
        c5.put("favourite foood bamboo",n);
        c5.put("a good swimmer",n);
        c5.put("screw-horned goat",n);
        c5.put("national animal",n);
        c5.put("short legs",n);
        c5.put("short tail",n);
        c5.put("greyish to muddy brown skin",n);
        c5.put("secnd largest land animal",n);
        c5.put("nose and eyes are the top of its head",n);
        c5.put("get water from plants",n);
        c5.put("king of a jungle",n);
        c5.put("carrying heavy loads",n);
        c5.put("reputation for stubbornness",n);
        c5.put("hoping and bouncing",n);
        c5.put("pouch",n);
        c5.put("big feets",n);
        c5.put("big cat species",n);
        c5.put("largest cat species in the world",n);
        c5.put("dark vertical stripes anf orange fur",n);
        c5.put("nocturnal animal",n);
        c5.put("solitary creature",n);
        c5.put(" 40 gallons in one go",n);
        c5.put("go for weeks without drinking water",n);

        c5.put("store fat and energy in parts of their bodies known as humps",n);
        c5.put("Can Hydrate Quickly",n);
        c5.put("picky eater",n);
        c5.put("four-compartment stomach",n);
        c5.put("dont have teeth on upper jaw",n);
        c5.put("dislike water",n);
        c5.put(" extremely intelligent animals capable of problem solving",n);
        c5.put(" best known for wool",n);
//----------------------------------------------------------
        HashMap c6 = new HashMap();
        c6.put("name","giraffe");
        c6.put("bnana fvrt food",n);
        c6.put("domestic animal",n);
        c6.put("social animal",y);
        c6.put("pet animal",n);
        c6.put("mammal",y);
        c6.put("cannot taste anything sweet",n);
        c6.put("carnivores",n);
        c6.put("primates",n);
        c6.put("fingerprints like human",n);
        c6.put("sleep while sitting",n);
        c6.put("omnivores",n);
        c6.put("leaping trees",n);
        c6.put("famous for loyality",n);
        c6.put("used by police",n);
        c6.put("herbivores",y);
        c6.put("black and white strips",n);
        c6.put("world's largest land animal",n);
        c6.put("large flat ears",n);
        c6.put("long trunk",n);
        c6.put("tallest",y);
        c6.put("long legs",y);
        c6.put("long neck",y);
        c6.put("brown spots on body",y);
        c6.put("livstock of meat and milk",n);
        c6.put("hides are used for making leather products",n);
        c6.put("sensitive skin",n);
        c6.put("poor eyesight",n);
        c6.put("roll in mud",n);
        c6.put("chew up wires",n);
        c6.put("eat paper",n);
        c6.put("sharp teeth",n);
        c6.put("small in size",n);
        c6.put("6 fingers",n);
        c6.put("love to eat",n);
        c6.put("favourite foood bamboo",n);
        c6.put("a good swimmer",n);
        c6.put("screw-horned goat",n);
        c6.put("national animal",n);
        c6.put("short legs",n);
        c6.put("short tail",n);
        c6.put("greyish to muddy brown skin",n);
        c6.put("secnd largest land animal",n);
        c6.put("nose and eyes are the top of its head",n);
        c6.put("get water from plants",n);
        c6.put("king of a jungle",n);
        c6.put("carrying heavy loads",n);
        c6.put("reputation for stubbornness",n);
        c6.put("hoping and bouncing",n);
        c6.put("pouch",n);
        c6.put("big feets",n);
        c6.put("big cat species",n);
        c6.put("largest cat species in the world",n);
        c6.put("dark vertical stripes anf orange fur",n);
        c6.put("nocturnal animal",n);
        c6.put("solitary creature",n);

        c6.put(" light coloured and have dark spots on their fur.",n);
        c6.put(" skilled climber",n);
        c6.put(" Leopards are the smallest of the large cat family",n);
        c6.put(" 40 gallons in one go",n);
        c6.put("go for weeks without drinking water",n);

        c6.put("store fat and energy in parts of their bodies known as humps",n);
        c6.put("Can Hydrate Quickly",n);
        c6.put("picky eater",n);
        c6.put("four-compartment stomach",n);
        c6.put("dont have teeth on upper jaw",n);
        c6.put("dislike water",n);
        c6.put(" extremely intelligent animals capable of problem solving",n);
        c6.put(" best known for wool",n);
//-------------------------------------------------------
        HashMap c7 = new HashMap();
        c7.put("name","cow");
        c7.put("bnana fvrt food",n);
        c7.put("domestic animal",y);
        c7.put("social animal",y);
        c7.put("pet animal",n);
        c7.put("mammal",y);
        c7.put("cannot taste anything sweet",n);
        c7.put("carnivores",n);
        c7.put("primates",n);
        c7.put("fingerprints like human",n);
        c7.put("sleep while sitting",n);
        c7.put("omnivores",n);
        c7.put("leaping trees",n);
        c7.put("famous for loyality",n);
        c7.put("used by police",n);
        c7.put("herbivores",y);
        c7.put("black and white strips",n);
        c7.put("world's largest land animal",n);
        c7.put("large flat ears",n);
        c7.put("long trunk",n);
        c7.put("tallest",n);
        c7.put("long legs",n);
        c7.put("long neck",n);
        c7.put("brown spots on body",n);
        c7.put("livstock of meat and milk",y);
        c7.put("hides are used for making leather products",y);
        c7.put("sensitive skin",n);
        c7.put("poor eyesight",n);
        c7.put("roll in mud",n);
        c7.put("chew up wires",n);
        c7.put("eat paper",n);
        c7.put("sharp teeth",n);
        c7.put("small in size",n);
        c7.put("6 fingers",n);
        c7.put("love to eat",n);
        c7.put("favourite foood bamboo",n);
        c7.put("a good swimmer",n);
        c7.put("screw-horned goat",n);
        c7.put("national animal",n);
        c7.put("short legs",n);
        c7.put("short tail",n);
        c7.put("greyish to muddy brown skin",n);
        c7.put("secnd largest land animal",n);
        c7.put("nose and eyes are the top of its head",n);
        c7.put("get water from plants",n);
        c7.put("king of a jungle",n);
        c7.put("carrying heavy loads",n);
        c7.put("reputation for stubbornness",n);
        c7.put("hoping and bouncing",n);
        c7.put("pouch",n);
        c7.put("big feets",n);
        c7.put("big cat species",n);
        c7.put("largest cat species in the world",n);
        c7.put("dark vertical stripes anf orange fur",n);
        c7.put("nocturnal animal",n);
        c7.put("solitary creature",n);

        c7.put(" light coloured and have dark spots on their fur.",n);
        c7.put(" skilled climber",n);
        c7.put(" Leopards are the smallest of the large cat family",n);
        c7.put(" 40 gallons in one go",n);
        c7.put("go for weeks without drinking water",n);

        c7.put("store fat and energy in parts of their bodies known as humps",n);
        c7.put("Can Hydrate Quickly",n);
        c7.put("picky eater",n);
        c7.put("four-compartment stomach",n);
        c7.put("dont have teeth on upper jaw",n);
        c7.put("dislike water",n);
        c7.put(" extremely intelligent animals capable of problem solving",n);
        c7.put(" best known for wool",n);
//-------------------------------------------------------
        HashMap c8 = new HashMap();
        c8.put("name","Rhinoceros");
        c8.put("bnana fvrt food",n);
        c8.put("domestic animal",n);
        c8.put("social animal",n);
        c8.put("pet animal",n);
        c8.put("mammal",y);
        c8.put("cannot taste anything sweet",n);
        c8.put("carnivores",n);
        c8.put("primates",n);
        c8.put("fingerprints like human",n);
        c8.put("sleep while sitting",n);
        c8.put("omnivores",n);
        c8.put("leaping trees",n);
        c8.put("famous for loyality",n);
        c8.put("used by police",n);
        c8.put("herbivores",y);
        c8.put("black and white strips",n);
        c8.put("world's largest land animal",n);
        c8.put("large flat ears",n);
        c8.put("long trunk",n);
        c8.put("tallest",n);
        c8.put("long legs",n);
        c8.put("long neck",n);
        c8.put("brown spots on body",n);
        c8.put("livstock of meat and milk",n);
        c8.put("hides are used for making leather products",n);
        c8.put("sensitive skin",y);
        c8.put("poor eyesight",y);
        c8.put("roll in mud",y);
        c8.put("chew up wires",n);
        c8.put("eat paper",n);
        c8.put("sharp teeth",n);
        c8.put("small in size",n);
        c8.put("6 fingers",n);
        c8.put("love to eat",n);
        c8.put("favourite foood bamboo",n);
        c8.put("a good swimmer",n);
        c8.put("screw-horned goat",n);
        c8.put("national animal",n);
        c8.put("short legs",n);
        c8.put("short tail",n);
        c8.put("greyish to muddy brown skin",n);
        c8.put("secnd largest land animal",n);
        c8.put("nose and eyes are the top of its head",n);
        c8.put("get water from plants",n);
        c8.put("king of a jungle",n);
        c8.put("carrying heavy loads",n);
        c8.put("reputation for stubbornness",n);
        c8.put("hoping and bouncing",n);
        c8.put("pouch",n);
        c8.put("big feets",n);
        c8.put("big cat species",n);
        c8.put("largest cat species in the world",n);
        c8.put("dark vertical stripes anf orange fur",n);
        c8.put("nocturnal animal",n);
        c8.put("solitary creature",n);

        c8.put(" light coloured and have dark spots on their fur.",n);
        c8.put(" skilled climber",n);
        c8.put(" Leopards are the smallest of the large cat family",n);
        c8.put(" 40 gallons in one go",n);
        c8.put("go for weeks without drinking water",n);

        c8.put("store fat and energy in parts of their bodies known as humps",n);
        c8.put("Can Hydrate Quickly",n);
        c8.put("picky eater",n);
        c8.put("four-compartment stomach",n);
        c8.put("dont have teeth on upper jaw",n);
        c8.put("dislike water",n);
        c8.put(" extremely intelligent animals capable of problem solving",n);
        c8.put(" best known for wool",n);
//-------------------------------------------------------
        HashMap c9 = new HashMap();
        c9.put("name","Rat");
        c9.put("bnana fvrt food",n);
        c9.put("domestic animal",n);
        c9.put("social animal",n);
        c9.put("pet animal",n);
        c9.put("mammal",y);
        c9.put("cannot taste anything sweet",n);
        c9.put("carnivores",n);
        c9.put("primates",n);
        c9.put("fingerprints like human",n);
        c9.put("sleep while sitting",n);
        c9.put("omnivores",n);
        c9.put("leaping trees",n);
        c9.put("famous for loyality",n);
        c9.put("used by police",n);
        c9.put("herbivores",y);
        c9.put("black and white strips",n);
        c9.put("world's largest land animal",n);
        c9.put("large flat ears",n);
        c9.put("long trunk",n);
        c9.put("tallest",n);
        c9.put("long legs",n);
        c9.put("long neck",n);
        c9.put("brown spots on body",n);
        c9.put("livstock of meat and milk",n);
        c9.put("hides are used for making leather products",n);
        c9.put("sensitive skin",n);
        c9.put("poor eyesight",n);
        c9.put("roll in mud",n);
        c9.put("chew up wires",y);
        c9.put("eat paper",y);
        c9.put("sharp teeth",y);
        c9.put("small in size",y);
        c9.put("6 fingers",n);
        c9.put("love to eat",n);
        c9.put("favourite foood bamboo",n);
        c9.put("a good swimmer",n);
        c9.put("screw-horned goat",n);
        c9.put("national animal",n);
        c9.put("short legs",n);
        c9.put("short tail",n);
        c9.put("greyish to muddy brown skin",n);
        c9.put("secnd largest land animal",n);
        c9.put("nose and eyes are the top of its head",n);
        c9.put("get water from plants",n);
        c9.put("king of a jungle",n);
        c9.put("carrying heavy loads",n);
        c9.put("reputation for stubbornness",n);
        c9.put("hoping and bouncing",n);
        c9.put("pouch",n);
        c9.put("big feets",n);
        c9.put("big cat species",n);
        c9.put("largest cat species in the world",n);
        c9.put("dark vertical stripes anf orange fur",n);
        c9.put("nocturnal animal",n);
        c9.put("solitary creature",n);

        c9.put(" light coloured and have dark spots on their fur.",n);
        c9.put(" skilled climber",n);
        c9.put(" Leopards are the smallest of the large cat family",n);
        c9.put(" 40 gallons in one go",n);
        c9.put("go for weeks without drinking water",n);

        c9.put("store fat and energy in parts of their bodies known as humps",n);
        c9.put("Can Hydrate Quickly",n);
        c9.put("picky eater",n);
        c9.put("four-compartment stomach",n);
        c9.put("dont have teeth on upper jaw",n);
        c9.put("dislike water",n);
        c9.put(" extremely intelligent animals capable of problem solving",n);
        c9.put(" best known for wool",n);
//-------------------------------------------------------
        HashMap c10 = new HashMap();
        c10.put("name","Panda");
        c10.put("bnana fvrt food",n);
        c10.put("domestic animal",n);
        c10.put("social animal",n);
        c10.put("pet animal",n);
        c10.put("mammal",y);
        c10.put("cannot taste anything sweet",n);
        c10.put("carnivores",n);
        c10.put("primates",n);
        c10.put("fingerprints like human",n);
        c10.put("sleep while sitting",n);
        c10.put("omnivores",n);
        c10.put("leaping trees",n);
        c10.put("famous for loyality",n);
        c10.put("used by police",n);
        c10.put("herbivores",y);
        c10.put("black and white strips",n);
        c10.put("world's largest land animal",n);
        c10.put("large flat ears",n);
        c10.put("long trunk",n);
        c10.put("tallest",n);
        c10.put("long legs",n);
        c10.put("long neck",n);
        c10.put("brown spots on body",n);
        c10.put("livstock of meat and milk",n);
        c10.put("hides are used for making leather products",n);
        c10.put("sensitive skin",n);
        c10.put("poor eyesight",n);
        c10.put("roll in mud",n);
        c10.put("chew up wires",n);
        c10.put("eat paper",n);
        c10.put("sharp teeth",n);
        c10.put("small in size",n);
        c10.put("6 fingers",y);
        c10.put("love to eat",y);
        c10.put("favourite foood bamboo",y);
        c10.put("a good swimmer",y);
        c10.put("screw-horned goat",n);
        c10.put("national animal",n);
        c10.put("short legs",n);
        c10.put("short tail",n);
        c10.put("greyish to muddy brown skin",n);
        c10.put("secnd largest land animal",n);
        c10.put("nose and eyes are the top of its head",n);
        c10.put("get water from plants",n);
        c10.put("king of a jungle",n);
        c10.put("carrying heavy loads",n);
        c10.put("reputation for stubbornness",n);
        c10.put("hoping and bouncing",n);
        c10.put("pouch",n);
        c10.put("big feets",n);
        c10.put("big cat species",n);
        c10.put("largest cat species in the world",n);
        c10.put("dark vertical stripes anf orange fur",n);
        c10.put("nocturnal animal",n);
        c10.put("solitary creature",n);

        c10.put(" light coloured and have dark spots on their fur.",n);
        c10.put(" skilled climber",n);
        c10.put(" Leopards are the smallest of the large cat family",n);
        c10.put(" 40 gallons in one go",n);
        c10.put("go for weeks without drinking water",n);

        c10.put("store fat and energy in parts of their bodies known as humps",n);
        c10.put("Can Hydrate Quickly",n);
        c10.put("picky eater",n);
        c10.put("four-compartment stomach",n);
        c10.put("dont have teeth on upper jaw",n);
        c10.put("dislike water",n);
        c10.put(" extremely intelligent animals capable of problem solving",n);
        c10.put(" best known for wool",n);
//-------------------------------------------------------
        HashMap c11 = new HashMap();
        c11.put("name","markhor");
        c11.put("bnana fvrt food",n);
        c11.put("domestic animal",n);
        c11.put("social animal",n);
        c11.put("pet animal",n);
        c11.put("mammal",y);
        c11.put("cannot taste anything sweet",n);
        c11.put("carnivores",n);
        c11.put("primates",n);
        c11.put("fingerprints like human",n);
        c11.put("sleep while sitting",n);
        c11.put("omnivores",n);
        c11.put("leaping trees",n);
        c11.put("famous for loyality",n);
        c11.put("used by police",n);
        c11.put("herbivores",y);
        c11.put("black and white strips",n);
        c11.put("world's largest land animal",n);
        c11.put("large flat ears",n);
        c11.put("long trunk",n);
        c11.put("tallest",n);
        c11.put("long legs",n);
        c11.put("long neck",n);
        c11.put("brown spots on body",n);
        c11.put("livstock of meat and milk",n);
        c11.put("hides are used for making leather products",n);
        c11.put("sensitive skin",n);
        c11.put("poor eyesight",n);
        c11.put("roll in mud",n);
        c11.put("chew up wires",n);
        c11.put("eat paper",n);
        c11.put("sharp teeth",n);
        c11.put("small in size",n);
        c11.put("6 fingers",n);
        c11.put("love to eat",n);
        c11.put("favourite foood bamboo",n);
        c11.put("a good swimmer",n);
        c11.put("screw-horned goat",y);
        c11.put("national animal",y);
        c11.put("short legs",n);
        c11.put("short tail",n);
        c11.put("greyish to muddy brown skin",n);
        c11.put("secnd largest land animal",n);
        c11.put("nose and eyes are the top of its head",n);
        c11.put("get water from plants",n);
        c11.put("king of a jungle",n);
        c11.put("carrying heavy loads",n);
        c11.put("reputation for stubbornness",n);
        c11.put("hoping and bouncing",n);
        c11.put("pouch",n);
        c11.put("big feets",n);
        c11.put("big cat species",n);
        c11.put("largest cat species in the world",n);
        c11.put("dark vertical stripes anf orange fur",n);
        c11.put("nocturnal animal",n);
        c11.put("solitary creature",n);

        c11.put(" light coloured and have dark spots on their fur.",n);
        c11.put(" skilled climber",n);
        c11.put(" Leopards are the smallest of the large cat family",n);
        c11.put(" 40 gallons in one go",n);
        c11.put("go for weeks without drinking water",n);

        c11.put("store fat and energy in parts of their bodies known as humps",n);
        c11.put("Can Hydrate Quickly",n);
        c11.put("picky eater",n);
        c11.put("four-compartment stomach",n);
        c11.put("dont have teeth on upper jaw",n);
        c11.put("dislike water",n);
        c11.put(" extremely intelligent animals capable of problem solving",n);
        c11.put(" best known for wool",n);
//-------------------------------------------------------
        HashMap c12 = new HashMap();
        c12.put("name","hippopotamus");
        c12.put("bnana fvrt food",n);
        c12.put("domestic animal",n);
        c12.put("social animal",y);
        c12.put("pet animal",n);
        c12.put("mammal",y);
        c12.put("cannot taste anything sweet",n);
        c12.put("carnivores",y);
        c12.put("primates",n);
        c12.put("fingerprints like human",n);
        c12.put("sleep while sitting",n);
        c12.put("omnivores",n);
        c12.put("leaping trees",n);
        c12.put("famous for loyality",n);
        c12.put("used by police",n);
        c12.put("herbivores",n);
        c12.put("black and white strips",n);
        c12.put("world's largest land animal",n);
        c12.put("large flat ears",n);
        c12.put("long trunk",n);
        c12.put("tallest",n);
        c12.put("long legs",n);
        c12.put("long neck",n);
        c12.put("brown spots on body",n);
        c12.put("livstock of meat and milk",n);
        c12.put("hides are used for making leather products",n);
        c12.put("sensitive skin",n);
        c12.put("poor eyesight",n);
        c12.put("roll in mud",n);
        c12.put("chew up wires",n);
        c12.put("eat paper",n);
        c12.put("sharp teeth",n);
        c12.put("small in size",n);
        c12.put("6 fingers",n);
        c12.put("love to eat",n);
        c12.put("favourite foood bamboo",n);
        c12.put("a good swimmer",n);
        c12.put("screw-horned goat",n);
        c12.put("national animal",n);
        c12.put("short legs",y);
        c12.put("short tail",y);
        c12.put("greyish to muddy brown skin",y);
        c12.put("secnd largest land animal",y);
        c12.put("nose and eyes are the top of its head",y);
        c12.put("get water from plants",n);
        c12.put("king of a jungle",n);

        c12.put("carrying heavy loads",n);
        c12.put("reputation for stubbornness",n);
        c12.put("hoping and bouncing",n);
        c12.put("pouch",n);
        c12.put("big feets",n);
        c12.put("big cat species",n);
        c12.put("largest cat species in the world",n);
        c12.put("dark vertical stripes anf orange fur",n);
        c12.put("nocturnal animal",n);
        c12.put("solitary creature",n);

        c12.put(" light coloured and have dark spots on their fur.",n);
        c12.put(" skilled climber",n);
        c12.put(" Leopards are the smallest of the large cat family",n);
        c12.put(" 40 gallons in one go",n);
        c12.put("go for weeks without drinking water",n);

        c12.put("store fat and energy in parts of their bodies known as humps",n);
        c12.put("Can Hydrate Quickly",n);
        c12.put("picky eater",n);
        c12.put("four-compartment stomach",n);
        c12.put("dont have teeth on upper jaw",n);
        c12.put("dislike water",n);
        c12.put(" extremely intelligent animals capable of problem solving",n);
        c12.put(" best known for wool",n);
//-------------------------------------------------------

        HashMap c13 = new HashMap();
        c13.put("name","lion");
        c13.put("bnana fvrt food",n);
        c13.put("domestic animal",n);
        c13.put("social animal",y);
        c13.put("pet animal",n);
        c13.put("mammal",y);
        c13.put("cannot taste anything sweet",n);
        c13.put("carnivores",n);
        c13.put("primates",n);
        c13.put("fingerprints like human",n);
        c13.put("sleep while sitting",n);
        c13.put("omnivores",y);
        c13.put("leaping trees",n);
        c13.put("famous for loyality",n);
        c13.put("used by police",n);
        c13.put("herbivores",n);
        c13.put("black and white strips",n);
        c13.put("world's largest land animal",n);
        c13.put("large flat ears",n);
        c13.put("long trunk",n);
        c13.put("tallest",n);
        c13.put("long legs",n);
        c13.put("long neck",n);
        c13.put("brown spots on body",n);
        c13.put("livstock of meat and milk",n);
        c13.put("hides are used for making leather products",n);
        c13.put("sensitive skin",n);
        c13.put("poor eyesight",n);
        c13.put("roll in mud",n);
        c13.put("chew up wires",n);
        c13.put("eat paper",n);
        c13.put("sharp teeth",n);
        c13.put("small in size",n);
        c13.put("6 fingers",n);
        c13.put("love to eat",n);
        c13.put("favourite foood bamboo",n);
        c13.put("a good swimmer",n);
        c13.put("screw-horned goat",n);
        c13.put("national animal",n);
        c13.put("short legs",n);
        c13.put("short tail",n);
        c13.put("greyish to muddy brown skin",n);
        c13.put("secnd largest land animal",n);
        c13.put("nose and eyes are the top of its head",n);
        c13.put("get water from plants",y);
        c13.put("king of a jungle",y);
        c13.put("carrying heavy loads",n);
        c13.put("reputation for stubbornness",n);
        c13.put("hoping and bouncing",n);
        c13.put("pouch",n);
        c13.put("big feets",n);
        c13.put("big cat species",n);
        c13.put("largest cat species in the world",n);
        c13.put("dark vertical stripes anf orange fur",n);
        c13.put("nocturnal animal",n);
        c13.put("solitary creature",n);

        c13.put(" light coloured and have dark spots on their fur.",n);
        c13.put(" skilled climber",n);
        c13.put(" Leopards are the smallest of the large cat family",n);
        c13.put(" 40 gallons in one go",n);
        c13.put("go for weeks without drinking water",n);

        c13.put("store fat and energy in parts of their bodies known as humps",n);
        c13.put("Can Hydrate Quickly",n);
        c13.put(" 40 gallons in one go",n);
        c13.put("go for weeks without drinking water",n);

        c13.put("store fat and energy in parts of their bodies known as humps",n);
        c13.put("Can Hydrate Quickly",n);

        c13.put("picky eater",n);
        c13.put("four-compartment stomach",n);
        c13.put("dont have teeth on upper jaw",n);
        c13.put("dislike water",n);
        c13.put(" extremely intelligent animals capable of problem solving",n);
        c13.put(" best known for wool",n);
//-------------------------------------------------------
        HashMap c14 = new HashMap();
        c14.put("name","donkey");
        c14.put("bnana fvrt food",n);
        c14.put("domestic animal",y);
        c14.put("social animal",y);
        c14.put("pet animal",n);
        c14.put("mammal",y);
        c14.put("cannot taste anything sweet",n);
        c14.put("carnivores",n);
        c14.put("primates",n);
        c14.put("fingerprints like human",n);
        c14.put("sleep while sitting",n);
        c14.put("omnivores",n);
        c14.put("leaping trees",n);
        c14.put("famous for loyality",n);
        c14.put("used by police",n);
        c14.put("herbivores",y);
        c14.put("black and white strips",n);
        c14.put("world's largest land animal",n);
        c14.put("large flat ears",n);
        c14.put("long trunk",n);
        c14.put("tallest",n);
        c14.put("long legs",n);
        c14.put("long neck",n);
        c14.put("brown spots on body",n);
        c14.put("livstock of meat and milk",n);
        c14.put("hides are used for making leather products",n);
        c14.put("sensitive skin",n);
        c14.put("poor eyesight",n);
        c14.put("roll in mud",n);
        c14.put("chew up wires",n);
        c14.put("eat paper",n);
        c14.put("sharp teeth",n);
        c14.put("small in size",n);
        c14.put("6 fingers",n);
        c14.put("love to eat",n);
        c14.put("favourite foood bamboo",n);
        c14.put("a good swimmer",n);
        c14.put("screw-horned goat",n);
        c14.put("national animal",n);
        c14.put("short legs",n);
        c14.put("short tail",n);
        c14.put("greyish to muddy brown skin",n);
        c14.put("secnd largest land animal",n);
        c14.put("nose and eyes are the top of its head",n);
        c14.put("get water from plants",n);
        c14.put("king of a jungle",n);
        c14.put("carrying heavy loads",y);
        c14.put("reputation for stubbornness",y);
        c14.put("hoping and bouncing",n);
        c14.put("pouch",n);
        c14.put("big feets",n);
        c14.put("big cat species",n);
        c14.put("largest cat species in the world",n);
        c14.put("dark vertical stripes anf orange fur",n);
        c14.put("nocturnal animal",n);
        c14.put("solitary creature",n);

        c14.put(" light coloured and have dark spots on their fur.",n);
        c14.put(" skilled climber",n);
        c14.put(" Leopards are the smallest of the large cat family",n);
        c14.put(" 40 gallons in one go",n);
        c14.put("go for weeks without drinking water",n);

        c14.put("store fat and energy in parts of their bodies known as humps",n);
        c14.put("Can Hydrate Quickly",n);
        c14.put("picky eater",n);
        c14.put("four-compartment stomach",n);
        c14.put("dont have teeth on upper jaw",n);
        c14.put("dislike water",n);
        c14.put(" extremely intelligent animals capable of problem solving",n);
        c14.put(" best known for wool",n);
//-------------------------------------------------------
        HashMap c15 = new HashMap();
        c15.put("name","kangroo");
        c15.put("bnana fvrt food",n);
        c15.put("domestic animal",n);
        c15.put("social animal",y);
        c15.put("pet animal",n);
        c15.put("mammal",y);
        c15.put("cannot taste anything sweet",n);
        c15.put("carnivores",n);
        c15.put("primates",n);
        c15.put("fingerprints like human",n);
        c15.put("sleep while sitting",n);
        c15.put("omnivores",n);
        c15.put("leaping trees",n);
        c15.put("famous for loyality",n);
        c15.put("used by police",n);
        c15.put("herbivores",y);
        c15.put("black and white strips",n);
        c15.put("world's largest land animal",n);
        c15.put("large flat ears",n);
        c15.put("long trunk",n);
        c15.put("tallest",n);
        c15.put("long legs",n);
        c15.put("long neck",n);
        c15.put("brown spots on body",n);
        c15.put("livstock of meat and milk",n);
        c15.put("hides are used for making leather products",n);
        c15.put("sensitive skin",n);
        c15.put("poor eyesight",n);
        c15.put("roll in mud",n);
        c15.put("chew up wires",n);
        c15.put("eat paper",n);
        c15.put("sharp teeth",n);
        c15.put("small in size",n);
        c15.put("6 fingers",n);
        c15.put("love to eat",n);
        c15.put("favourite foood bamboo",n);
        c15.put("a good swimmer",n);
        c15.put("screw-horned goat",n);
        c15.put("national animal",n);
        c15.put("short legs",n);
        c15.put("short tail",n);
        c15.put("greyish to muddy brown skin",n);
        c15.put("secnd largest land animal",n);
        c15.put("nose and eyes are the top of its head",n);
        c15.put("get water from plants",n);
        c15.put("king of a jungle",n);
        c15.put("carrying heavy loads",n);
        c15.put("reputation for stubbornness",n);
        c15.put("hoping and bouncing ",y);
        c15.put("pouch",y);
        c15.put("big feets",y);
        c15.put("big cat species",n);
        c15.put("largest cat species in the world",n);
        c15.put("dark vertical stripes anf orange fur",n);
        c15.put("nocturnal animal",n);
        c15.put("solitary creature",n);

        c15.put(" light coloured and have dark spots on their fur.",n);
        c15.put(" skilled climber",n);
        c15.put(" Leopards are the smallest of the large cat family",n);
        c15.put(" 40 gallons in one go",n);
        c15.put("go for weeks without drinking water",n);

        c15.put("store fat and energy in parts of their bodies known as humps",n);
        c15.put("Can Hydrate Quickly",n);
        c15.put("picky eater",n);
        c15.put("four-compartment stomach",n);
        c15.put("dont have teeth on upper jaw",n);
        c15.put("dislike water",n);
        c15.put(" extremely intelligent animals capable of problem solving",n);
        c15.put(" best known for wool",n);
//---------------------------------------------------
        HashMap c16 = new HashMap();
        c16.put("name","Tiger");
        c16.put("bnana fvrt food",n);
        c16.put("domestic animal",n);
        c16.put("social animal",n);
        c16.put("pet animal",n);
        c16.put("mammal",y);
        c16.put("cannot taste anything sweet",n);
        c16.put("carnivores",y);
        c16.put("primates",n);
        c16.put("fingerprints like human",n);
        c16.put("sleep while sitting",n);
        c16.put("omnivores",n);
        c16.put("leaping trees",n);
        c16.put("famous for loyality",n);
        c16.put("used by police",n);
        c16.put("herbivores",n);
        c16.put("black and white strips",n);
        c16.put("world's largest land animal",n);
        c16.put("large flat ears",n);
        c16.put("long trunk",n);
        c16.put("tallest",n);
        c16.put("long legs",n);
        c16.put("long neck",n);
        c16.put("brown spots on body",n);
        c16.put("livstock of meat and milk",n);
        c16.put("hides are used for making leather products",n);
        c16.put("sensitive skin",n);
        c16.put("poor eyesight",n);
        c16.put("roll in mud",n);
        c16.put("chew up wires",n);
        c16.put("eat paper",n);
        c16.put("sharp teeth",n);
        c16.put("small in size",n);
        c16.put("6 fingers",n);
        c16.put("love to eat",n);
        c16.put("favourite foood bamboo",n);
        c16.put("a good swimmer",y);
        c16.put("screw-horned goat",n);
        c16.put("national animal",n);
        c16.put("short legs",n);
        c16.put("short tail",n);
        c16.put("greyish to muddy brown skin",n);
        c16.put("secnd largest land animal",n);
        c16.put("nose and eyes are the top of its head",n);
        c16.put("get water from plants",n);
        c16.put("king of a jungle",n);
        c16.put("carrying heavy loads",n);
        c16.put("reputation for stubbornness",n);
        c16.put("hoping and bouncing",n);
        c16.put("pouch",n);
        c16.put("big feets",n);
        c16.put("big cat species",y);
        c16.put("largest cat species in the world",y);
        c16.put("dark vertical stripes anf orange fur",y);
        c16.put("nocturnal animal",y);
        c16.put("solitary creature",y);

        c16.put(" light coloured and have dark spots on their fur.",n);
        c16.put(" skilled climber",n);
        c16.put(" Leopards are the smallest of the large cat family",n);
        c16.put(" 40 gallons in one go",n);
        c16.put("go for weeks without drinking water",n);

        c16.put("store fat and energy in parts of their bodies known as humps",n);
        c16.put("Can Hydrate Quickly",n);
        c16.put("picky eater",n);
        c16.put("four-compartment stomach",n);
        c16.put("dont have teeth on upper jaw",n);
        c16.put("dislike water",n);
        c16.put(" extremely intelligent animals capable of problem solving",n);
        c16.put(" best known for wool",n);
        //---------------------------------------------------

        HashMap c17 = new HashMap();
        c17.put("name","Leopard");
        c17.put("bnana fvrt food",n);
        c17.put("domestic animal",n);
        c17.put("social animal",n);
        c17.put("pet animal",n);
        c17.put("mammal",y);
        c17.put("cannot taste anything sweet",n);
        c17.put("carnivores",y);
        c17.put("primates",n);
        c17.put("fingerprints like human",n);
        c17.put("sleep while sitting",n);
        c17.put("omnivores",n);
        c17.put("leaping trees",n);
        c17.put("famous for loyality",n);
        c17.put("used by police",n);
        c17.put("herbivores",n);
        c17.put("black and white strips",n);
        c17.put("world's largest land animal",n);
        c17.put("large flat ears",n);
        c17.put("long trunk",n);
        c17.put("tallest",n);
        c17.put("long legs",n);
        c17.put("long neck",n);
        c17.put("brown spots on body",n);
        c17.put("livstock of meat and milk",n);
        c17.put("hides are used for making leather products",n);
        c17.put("sensitive skin",n);
        c17.put("poor eyesight",n);
        c17.put("roll in mud",n);
        c17.put("chew up wires",n);
        c17.put("eat paper",n);
        c17.put("sharp teeth",n);
        c17.put("small in size",n);
        c17.put("6 fingers",n);
        c17.put("love to eat",n);
        c17.put("favourite foood bamboo",n);
        c17.put("a good swimmer",y);
        c17.put("screw-horned goat",n);
        c17.put("national animal",n);
        c17.put("short legs",n);
        c17.put("short tail",n);
        c17.put("greyish to muddy brown skin",n);
        c17.put("secnd largest land animal",n);
        c17.put("nose and eyes are the top of its head",n);
        c17.put("get water from plants",n);
        c17.put("king of a jungle",n);
        c17.put("carrying heavy loads",n);
        c17.put("reputation for stubbornness",n);
        c17.put("hoping and bouncing",n);
        c17.put("pouch",n);
        c17.put("big feets",n);
        c17.put("big cat species",y);
        c17.put("largest cat species in the world",n);
        c17.put("dark vertical stripes anf orange fur",n);
        c17.put("nocturnal animal",y);
        c17.put("solitary creature",y);
        c17.put(" light coloured and have dark spots on their fur.",y);
        c17.put(" skilled climber",y);
        c17.put(" Leopards are the smallest of the large cat family",y);
        c17.put(" 40 gallons in one go",n);
        c17.put("go for weeks without drinking water",n);

        c17.put("store fat and energy in parts of their bodies known as humps",n);
        c17.put("Can Hydrate Quickly",n);
        c17.put("picky eater",n);
        c17.put("four-compartment stomach",n);
        c17.put("dont have teeth on upper jaw",n);
        c17.put("dislike water",n);
        c17.put(" extremely intelligent animals capable of problem solving",n);
        c17.put(" best known for wool",n);
        //---------------------------------------------------


        HashMap c18 = new HashMap();
        c18.put("name","camel");
        c18.put("bnana fvrt food",n);
        c18.put("domestic animal",n);
        c18.put("social animal",y);
        c18.put("pet animal",n);
        c18.put("mammal",y);
        c18.put("cannot taste anything sweet",n);
        c18.put("carnivores",n);
        c18.put("primates",n);
        c18.put("fingerprints like human",n);
        c18.put("sleep while sitting",n);
        c18.put("omnivores",n);
        c18.put("leaping trees",n);
        c18.put("famous for loyality",n);
        c18.put("used by police",n);
        c18.put("herbivores",y);
        c18.put("black and white strips",n);
        c18.put("world's largest land animal",n);
        c18.put("large flat ears",n);
        c18.put("long trunk",n);
        c18.put("tallest",n);
        c18.put("long legs",n);
        c18.put("long neck",n);
        c18.put("brown spots on body",n);
        c18.put("livstock of meat and milk",n);
        c18.put("hides are used for making leather products",n);
        c18.put("sensitive skin",n);
        c18.put("poor eyesight",n);
        c18.put("roll in mud",n);
        c18.put("chew up wires",n);
        c18.put("eat paper",n);
        c18.put("sharp teeth",n);
        c18.put("small in size",n);
        c18.put("6 fingers",n);
        c18.put("love to eat",n);
        c18.put("favourite foood bamboo",n);
        c18.put("a good swimmer",n);
        c18.put("screw-horned goat",n);
        c18.put("national animal",n);
        c18.put("short legs",n);
        c18.put("short tail",n);
        c18.put("greyish to muddy brown skin",n);
        c18.put("secnd largest land animal",n);
        c18.put("nose and eyes are the top of its head",n);
        c18.put("get water from plants",n);
        c18.put("king of a jungle",n);
        c18.put("carrying heavy loads",n);
        c18.put("reputation for stubbornness",n);
        c18.put("hoping and bouncing",n);
        c18.put("pouch",n);
        c18.put("big feets",n);
        c18.put("big cat species",n);
        c18.put("largest cat species in the world",n);
        c18.put("dark vertical stripes anf orange fur",n);
        c18.put("nocturnal animal",n);
        c18.put("solitary creature",n);
        c18.put(" light coloured and have dark spots on their fur.",n);
        c18.put(" skilled climber",n);
        c18.put(" Leopards are the smallest of the large cat family",n);
        c18.put(" 40 gallons in one go",y);
        c18.put("go for weeks without drinking water",y);

        c18.put("store fat and energy in parts of their bodies known as humps",y);
        c18.put("Can Hydrate Quickly",y);
        c18.put("picky eater",n);
        c18.put("four-compartment stomach",n);
        c18.put("dont have teeth on upper jaw",n);
        c18.put("dislike water",n);
        c18.put(" extremely intelligent animals capable of problem solving",n);
        c18.put(" best known for wool",n);
        //-----------------------------------------------------


        HashMap c19 = new HashMap();
        c19.put("name","goat");
        c19.put("bnana fvrt food",n);
        c19.put("domestic animal",y);
        c19.put("social animal",y);
        c19.put("pet animal",n);
        c19.put("mammal",y);
        c19.put("cannot taste anything sweet",n);
        c19.put("carnivores",y);
        c19.put("primates",n);
        c19.put("fingerprints like human",n);
        c19.put("sleep while sitting",n);
        c19.put("omnivores",n);
        c19.put("leaping trees",n);
        c19.put("famous for loyality",n);
        c19.put("used by police",n);
        c19.put("herbivores",n);
        c19.put("black and white strips",n);
        c19.put("world's largest land animal",n);
        c19.put("large flat ears",n);
        c19.put("long trunk",n);
        c19.put("tallest",n);
        c19.put("long legs",n);
        c19.put("long neck",n);
        c19.put("brown spots on body",n);
        c19.put("livstock of meat and milk",n);
        c19.put("hides are used for making leather products",n);
        c19.put("sensitive skin",n);
        c19.put("poor eyesight",n);
        c19.put("roll in mud",n);
        c19.put("chew up wires",n);
        c19.put("eat paper",n);
        c19.put("sharp teeth",n);
        c19.put("small in size",n);
        c19.put("6 fingers",n);
        c19.put("love to eat",n);
        c19.put("favourite foood bamboo",n);
        c19.put("a good swimmer",n);
        c19.put("screw-horned goat",n);
        c19.put("national animal",n);
        c19.put("short legs",n);
        c19.put("short tail",n);
        c19.put("greyish to muddy brown skin",n);
        c19.put("secnd largest land animal",n);
        c19.put("nose and eyes are the top of its head",n);
        c19.put("get water from plants",n);
        c19.put("king of a jungle",n);
        c19.put("carrying heavy loads",n);
        c19.put("reputation for stubbornness",n);
        c19.put("hoping and bouncing",n);
        c19.put("pouch",n);
        c19.put("big feets",n);
        c19.put("big cat species",n);
        c19.put("largest cat species in the world",n);
        c19.put("dark vertical stripes anf orange fur",n);
        c19.put("nocturnal animal",n);
        c19.put("solitary creature",n);
        c19.put(" light coloured and have dark spots on their fur.",n);
        c19.put(" skilled climber",n);
        c19.put(" Leopards are the smallest of the large cat family",n);
        c19.put(" 40 gallons in one go",n);

        c19.put("go for weeks without drinking water",n);

        c19.put("store fat and energy in parts of their bodies known as humps",n);
        c19.put("Can Hydrate Quickly",n);
        c19.put("picky eater",y);
        c19.put("four-compartment stomach",y);
        c19.put("dont have teeth on upper jaw",y);
        c19.put("dislike water",y);
        c19.put(" extremely intelligent animals capable of problem solving",n);
        c19.put(" best known for wool",n);
        //------------------------------------------------


        HashMap c20 = new HashMap();
        c20.put("name","sheep");
        c20.put("bnana fvrt food",n);
        c20.put("domestic animal",y);
        c20.put("social animal",y);
        c20.put("pet animal",n);
        c20.put("mammal",y);
        c20.put("cannot taste anything sweet",n);
        c20.put("carnivores",y);
        c20.put("primates",n);
        c20.put("fingerprints like human",n);
        c20.put("sleep while sitting",n);
        c20.put("omnivores",n);
        c20.put("leaping trees",n);
        c20.put("famous for loyality",n);
        c20.put("used by police",n);
        c20.put("herbivores",n);
        c20.put("black and white strips",n);
        c20.put("world's largest land animal",n);
        c20.put("large flat ears",n);
        c20.put("long trunk",n);
        c20.put("tallest",n);
        c20.put("long legs",n);
        c20.put("long neck",n);
        c20.put("brown spots on body",n);
        c20.put("livstock of meat and milk",n);
        c20.put("hides are used for making leather products",n);
        c20.put("sensitive skin",n);
        c20.put("poor eyesight",n);
        c20.put("roll in mud",n);
        c20.put("chew up wires",n);
        c20.put("eat paper",n);
        c20.put("sharp teeth",n);
        c20.put("small in size",n);
        c20.put("6 fingers",n);
        c20.put("love to eat",n);
        c20.put("favourite foood bamboo",n);
        c20.put("a good swimmer",n);
        c20.put("screw-horned goat",n);
        c20.put("national animal",n);
        c20.put("short legs",n);
        c20.put("short tail",n);
        c20.put("greyish to muddy brown skin",n);
        c20.put("secnd largest land animal",n);
        c20.put("nose and eyes are the top of its head",n);
        c20.put("get water from plants",n);
        c20.put("king of a jungle",n);
        c20.put("carrying heavy loads",n);
        c20.put("reputation for stubbornness",n);
        c20.put("hoping and bouncing",n);
        c20.put("pouch",n);
        c20.put("big feets",n);
        c20.put("big cat species",n);
        c20.put("largest cat species in the world",n);
        c20.put("dark vertical stripes anf orange fur",n);
        c20.put("nocturnal animal",n);
        c20.put("solitary creature",n);
        c20.put(" light coloured and have dark spots on their fur.",n);
        c20.put(" skilled climber",n);
        c20.put(" Leopards are the smallest of the large cat family",n);
        c20.put(" 40 gallons in one go",n);

        c20.put("go for weeks without drinking water",n);

        c20.put("store fat and energy in parts of their bodies known as humps",n);
        c20.put("Can Hydrate Quickly",n);
        c20.put("picky eater",n);
        c20.put("four-compartment stomach",y);
        c20.put("dont have teeth on upper jaw",y);
        c20.put("dislike water",n);
        c20.put(" extremely intelligent animals capable of problem solving",y);
        c20.put(" best known for wool",y);

        //--------------------------
        ArrayList database = new ArrayList();
        database.add(c1);
        database.add(c2);
        database.add(c3);
        database.add(c4);
        database.add(c5);
        database.add(c6);
        database.add(c7);
        database.add(c8);
        database.add(c9);
        database.add(c10);
        database.add(c11);
        database.add(c12);
        database.add(c13);
        database.add(c14);
        database.add(c15);
        database.add(c16);
        database.add(c17);
        database.add(c18);
        database.add(c19);
        database.add(c20);
//---------------------------------------------------
        Scanner sc = new Scanner(System.in);
        System.out.println("Is your animal favourite food is banana? : ");
        take_input(sc.nextInt(), "bnana fvrt food", database);
        System.out.println("Is your animal domestic animal? : ");
        take_input(sc.nextInt(), "domestic animal", database);
        System.out.println("Is your animal social animal ? : ");
        take_input(sc.nextInt(), "social animal", database);

        System.out.println("Is your animal pet animal ? : ");
        take_input(sc.nextInt(), "pet animal", database);

        System.out.println("Is your animal mammal ? : ");
        take_input(sc.nextInt(), "mammal", database);

        System.out.println("Is your animal cannot taste anything sweet ? : ");
        take_input(sc.nextInt(), "cannot taste anything sweet", database);
        System.out.println("Is your animal carnivores ? : ");
        take_input(sc.nextInt(), "carnivores", database);

        System.out.println("Is your animal primates? : ");
        take_input(sc.nextInt(), "primates", database);

        System.out.println("Is your animal have finerprints like humans ? : ");
        take_input(sc.nextInt(), "fingerprints like human", database);

        System.out.println("Is your animal can sleep while sitting ? : ");
        take_input(sc.nextInt(), "sleep while sitting", database);

        System.out.println("Is your animal omnivores ? : ");
        take_input(sc.nextInt(), "omnivores", database);

        System.out.println("Is your animal known for leaping with trees with ease ? : ");
        take_input(sc.nextInt(), "leaping trees", database);

        System.out.println("Is your animal famous for loyality ? : ");
        take_input(sc.nextInt(), "famous for loyality", database);

        System.out.println("Is your animal used by police to detect  ? : ");
        take_input(sc.nextInt(), "used by police", database);

        System.out.println("Is your animal herbivores  ? : ");
        take_input(sc.nextInt(), "herbivores", database);
        System.out.println("Is your animal have black and white strips on body  ? : ");
        take_input(sc.nextInt(), "used by police", database);
        System.out.println("Is your animal world's largest land animal  ? : ");
        take_input(sc.nextInt(), "world's largest land animal", database);
        System.out.println("Is your animal have large flat ears ? : ");
        take_input(sc.nextInt(), "large flat ears", database);
        System.out.println("Is your animal have long trunk ? : ");
        take_input(sc.nextInt(), "long trunk", database);

        System.out.println("Is your animal world's tallest animal ? : ");
        take_input(sc.nextInt(), "tallest", database);
        System.out.println("Is your animal have long legs ? : ");
        take_input(sc.nextInt(), "long legs", database);
        System.out.println("Is your animal have long neck ? : ");
        take_input(sc.nextInt(), "long neck", database);
        System.out.println("Is your animal have brown spots on body ? : ");
        take_input(sc.nextInt(), "brown spots on body", database);
        c7.put("livstock of meat and milk",y);
        c7.put("hides are used for making leather products",y);
        System.out.println("Is your animal livstock of meat and milk ? : ");
        take_input(sc.nextInt(), "livstock of meat and milk", database);
        System.out.println("Is your animal's hides are used for making leather products ? : ");
        take_input(sc.nextInt(), "hides are used for making leather products", database);

        System.out.println("Is your animal have sensitive skin ? : ");
        take_input(sc.nextInt(), "sensitive skin", database);
        System.out.println("Is your animal have poor eyesight? : ");
        take_input(sc.nextInt(), "poor eyesight", database);
        System.out.println("Is your animal roll in mud to protect skin from sunburn? : ");
        take_input(sc.nextInt(), "roll in mud", database);
        System.out.println("Is your animal chew up wires? : ");
        take_input(sc.nextInt(), "chew up wires", database);
        System.out.println("Is your animal eat paper? : ");
        take_input(sc.nextInt(), "eat paper", database);
        System.out.println("Is your animal have sharp teeth? : ");
        take_input(sc.nextInt(), "sharp teeth", database);
        System.out.println("Is your animal small in size? : ");
        take_input(sc.nextInt(), "small in size", database);
        System.out.println("Is your animal hav 6 fingers? : ");
        take_input(sc.nextInt(), "6 fingers", database);
        System.out.println("Is your animal love to eat? : ");
        take_input(sc.nextInt(), "love to eat", database);
        System.out.println("Is your animal favourite foood bamboo? : ");
        take_input(sc.nextInt(), "favourite foood bamboo", database);
        System.out.println("Is your animal a good swimmer? : ");
        take_input(sc.nextInt(), "a good swimmer", database);

        System.out.println("Is your animal also known as screw-horned goat? : ");
        take_input(sc.nextInt(), "screw-horned goat", database);
        System.out.println("Is your animal a national animal? : ");
        take_input(sc.nextInt(), "national animal", database);
        System.out.println("Is your animal have short legs? : ");
        take_input(sc.nextInt(), "short legs", database);
        System.out.println("Is your animal have short tail? : ");
        take_input(sc.nextInt(), "short tail", database);
        System.out.println("Is your animal have greyish to muddy brown skin? : ");
        take_input(sc.nextInt(), "greyish to muddy brown skin", database);
        System.out.println("Is your animal known as secnd largest land animal? : ");
        take_input(sc.nextInt(), "secnd largest land animal", database);
        System.out.println("Is your animal have nose and eyes on the top of its head? : ");
        take_input(sc.nextInt(), "nose and eyes are the top of its head", database);

        System.out.println("Is your animal can get water from plants? : ");
        take_input(sc.nextInt(), "get water from plants", database);
        System.out.println("Is your animal known as king of a jungle : ");
        take_input(sc.nextInt(), "king of a jungle", database);

        System.out.println("Is your animal famous for carrying heavy loads : ");
        take_input(sc.nextInt(), "carrying heavy loads", database);
        System.out.println("Is your animal have reputation for stubbornness : ");
        take_input(sc.nextInt(), "reputation for stubbornness", database);


        System.out.println("Is your animal hoping and bouncing on their hind legs : ");
        take_input(sc.nextInt(), "hoping and bouncing", database);
        System.out.println("Is your animal have pouch in which they kept baby kangroo : ");
        take_input(sc.nextInt(), "pouch", database);
        System.out.println("Is your animal have big feets : ");
        take_input(sc.nextInt(), "big feets", database);

        System.out.println("Is your animal big cat species: ");
        take_input(sc.nextInt(), "big cat species", database);

        System.out.println("Is your animal considered as largest cat species in the world : ");
        take_input(sc.nextInt(), "largest cat species in the world", database);
        System.out.println("Is your animal have dark vertical stripes and orange fur on body: ");
        take_input(sc.nextInt(), "dark vertical stripes anf orange fur", database);
        System.out.println("Is your animal nocturnal animal : ");
        take_input(sc.nextInt(), "nocturnal animal", database);
        System.out.println("Is your animal solitary creature : ");
        take_input(sc.nextInt(), "solitary creature", database);

        System.out.println("Is your animal have light coloured and have dark spots on their fur. : ");
        take_input(sc.nextInt(), "light coloured and have dark spots on their fur.", database);
        System.out.println("Is your animal skilled climber : ");
        take_input(sc.nextInt(), "skilled climber", database);
        System.out.println("Is your animal are the smallest of the large cat family : ");
        take_input(sc.nextInt(), "Leopards are the smallest of the large cat family", database);

        System.out.println("Is your animal can drink 40 gallons of water in one go : ");
        take_input(sc.nextInt(), "40 gallons in one go", database);

        System.out.println("Is your animal can go for weeks without drinking water : ");
        take_input(sc.nextInt(), "go for weeks without drinking water", database);

        System.out.println("Is your animal store fat and energy in parts of their bodies known as humps : ");
        take_input(sc.nextInt(), "store fat and energy in parts of their bodies known as humps", database);

        System.out.println("Is your animal Can Hydrate Quickly: ");
        take_input(sc.nextInt(), "Can Hydrate Quickly", database);


        c19.put("",y);
        c19.put("-",y);
        c19.put("dont have teeth on upper jaw",y);
        c19.put("dislike water",y);
        System.out.println("Is your animal picky eater: ");
        take_input(sc.nextInt(), "picky eater", database);

        System.out.println("Is your animal have four-compartment stomach: ");
        take_input(sc.nextInt(), "four-compartment stomach", database);

        System.out.println("Is your animal dont have teeth on upper jaw: ");
        take_input(sc.nextInt(), "dont have teeth on upper jaw", database);

        System.out.println("Is your animal dislike water: ");
        take_input(sc.nextInt(), "dislike water", database);

        System.out.println("Is your animal extremely intelligent animals capable of problem solving: ");
        take_input(sc.nextInt(), "extremely intelligent animals capable of problem solving", database);

        System.out.println("Is your animal best known for wool ");
        take_input(sc.nextInt(), "best known for wool", database);
    }

    public static void take_input(int answer, String property, ArrayList<HashMap<String, Object>> database) {
        boolean ans = answer == 1;
        ArrayList<HashMap<String, Object>> toRemove = new ArrayList<>();

        for (HashMap<String, Object> character : database) {
            boolean prop = (boolean) character.get(property);
            if (prop != ans) {
                toRemove.add(character);
            }
        }

        database.removeAll(toRemove);

        if (database.size() == 1) {
            HashMap<String, Object> character = database.get(0);
            String name = (String) character.get("name");
            System.out.println("Your animal is " + name);
            System.exit(0);
        } else if (database.isEmpty()) {
            System.out.println("Your animal does not exist.");
            System.exit(0);
        }
    }
}


